-- Service type moves from Request to RequestItem so one request can mix services.
-- Hand-written rather than autogenerated: the backfill below MUST run between the
-- ADD and the DROP, otherwise every historical line reverts to NORMAL while its
-- frozen unitPrice still holds a dry-clean/pressing price — corrupting the past
-- invoices and reports the hotel bills from.

-- 1. Add the column, defaulted so existing rows stay valid.
ALTER TABLE "request_items" ADD COLUMN "serviceType" "ServiceType" NOT NULL DEFAULT 'NORMAL';

-- 2. Backfill: every line inherits the service its parent request was placed under.
UPDATE "request_items" AS ri
SET "serviceType" = r."serviceType"
FROM "requests" AS r
WHERE ri."requestId" = r."id";

-- 3. Only now is the request-level column redundant.
ALTER TABLE "requests" DROP COLUMN "serviceType";
